all:
  hosts:
    web1:
      ansible_host: ec2-52-34-1-23.us-west-2.compute.amazonaws.com
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/aws
    web2:
      ansible_host: ec2-54-214-115-127.us-west-2.compute.amazonaws.com
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/aws
