all:
  hosts:
    web1:
      ansible_host: ec2-44-244-210-248.us-west-2.compute.amazonaws.com
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/aws
    web2:
      ansible_host: ec2-44-244-194-110.us-west-2.compute.amazonaws.com
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/aws
